//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarangayanSignIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarangayanSignIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAABbUlEQVR4nO3ZsQ3CMBQE0TGCCCFh
        ///uFJcgDkIAB8dGeDUpuHkPX43rtPmeM2ZDKZTKZTKZTKZf4guWpjz5vKzGqN9o4TjBLzA9A5K4AA
        ///0g0pIBsBDEghgQZBzAMkQGIBZBA0gEwQGCAYxINkEBoIh4QwCJhAcgEYQB0gEQA5wAZAgdgB2ID
        ///7AD0AA0gM4wBlADNIAyQAZIBsAAEUDMABlADJABkgGwAAaQAyQAZIBsAAEUDMABlADJABkgGwAA
        ///aQAyQAZIBsAAEUDMABlADJABkgGwAAaQAyQAZIBsAAEUDMABlADJABkgGwAAaQAyQAZIBsAAEUD
        ///MABlADJABkgGwAAaQAyQAZIBsAAEUDMABlADJABkgGwAAaQAyQAZIBsAAEUDEAc0trA9BnmN1gu
        ///hXYAAAAASUVORK5CYII=.
        /// </summary>
        internal static string barangayan_logo {
            get {
                return ResourceManager.GetString("barangayan_logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAABNVBMVEUAAAD///8AAAD5+fn4+Pj7
        ///+/v39/f09PTw8PDv7+/s7Ozq6urx8fHv7+/p6enr6+vu7u7v7+/w8PDu7u7t7e3t7e3u7u7t7e3s
        ///7Ozq6urv7+/s7Ozq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq
        ///6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq
        ///6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq
        ///6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq
        ///6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq6urq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAABHFBMVEUAAAD////////////////////////////////////
        //////////////////////////////////////////////////////////////////////////////////////////////////
        //////////////////////////////////////////////////////////////9u38bEAAAAQXRSTlMAAQIDBAUGBwgJCgsM
        ///DQ4PEBESExQVFhcYGRobHB0eHyAhIiMkJSYnKCkqKywtLi8wMTIzNDU2Nzg5Ojs8PT4/QEZFQUJD
        ///REVGR0hJSktMTU5PUFFSU1RVVldYWVpbXGFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6e3x9fn8A
        ///AAAAAAAAAABy2CwWAAAAWElEQVQY02NgAAJGJiYGBgaGBiZGJgYGhgYmBgYGBiYGJgY [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string google {
            get {
                return ResourceManager.GetString("google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAABOFBMVEUAAAD////////////////////////////////////
        //////////////////////////////////////////////////////////////////////////////////////////////////
        //////////////////////////////////////////////////////////////////////////////////////////////////
        //////////////////////////////////////////////9nBh5fAAAAQHRSTlMAAQIDBAUGBwgJCgsMDQ4PEBESExQVFhcY
        ///GRobHB0eHyAhIiMkJSYnKCkqKywtLi8wMTIzNDU2Nzg5Ojs8PT4/QEZFQUJDREVGR0hJSktMTU5P
        ///UAAAAAAAAAAAj3AJjwAAAFNJREFUGJVjYAACJiYmFgYGBgaG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Lock {
            get {
                return ResourceManager.GetString("Lock", resourceCulture);
            }
        }
    }
}
